from __future__ import annotations

import json
import shutil
from datetime import date
from pathlib import Path
from typing import Any

from insight_dashboard.validation import validate_digest

ROOT = Path(__file__).resolve().parents[1]


def _daily_digest_path(root: Path, date_value: str) -> Path:
    parsed = date.fromisoformat(date_value)
    return root / "data" / "daily" / f"{parsed.year:04d}" / f"{parsed.month:02d}" / f"{date_value}.json"


def _render_digest_imports(root: Path, archive: dict[str, Any]) -> str:
    imports: list[str] = []
    names: list[str] = []
    dates: list[str] = []
    for entry in archive.get("entries", []):
        date_value = entry["date"]
        daily_path = _daily_digest_path(root, date_value)
        if not daily_path.exists():
            raise FileNotFoundError(f"archive entry has no daily digest: {daily_path.relative_to(root)}")
        payload = json.loads(daily_path.read_text(encoding="utf-8"))
        validated = validate_digest(payload)
        if validated.date != date_value:
            raise ValueError(f"archive date and digest date disagree: {date_value}")
        name = f"digest{date_value.replace('-', '')}"
        relative_path = Path("../daily") / date_value[:4] / date_value[5:7] / f"{date_value}.json"
        imports.append(f'import {name} from "{relative_path.as_posix()}";')
        names.append(f"  {name},")
        dates.append(f'  "{date_value}",')

    if not imports:
        raise ValueError("archive must contain at least one daily digest")

    return "\n".join(
        [
            "/* This file is generated by scripts/build_public_data.py. Do not edit manually. */",
            "",
            *imports,
            "",
            "export const generatedDigests = [",
            *names,
            "] as const;",
            "",
            "export const generatedDigestDates = [",
            *dates,
            "] as const;",
            "",
        ]
    )


def main() -> int:
    latest = ROOT / "data" / "manifests" / "latest.json"
    payload = json.loads(latest.read_text(encoding="utf-8"))
    validate_digest(payload)
    archive_path = ROOT / "data" / "manifests" / "archive-index.json"
    archive = json.loads(archive_path.read_text(encoding="utf-8"))
    entries = archive.get("entries") or []
    if not entries or entries[0].get("date") != payload["date"]:
        raise ValueError("latest digest date must be the first archive entry")

    generated_path = ROOT / "data" / "manifests" / "digests.generated.ts"
    generated_path.write_text(_render_digest_imports(ROOT, archive), encoding="utf-8")

    target = ROOT / "public" / "data" / "latest.json"
    target.parent.mkdir(parents=True, exist_ok=True)
    shutil.copyfile(latest, target)
    print(
        f"validated {len(entries)} digests, generated {generated_path.relative_to(ROOT)}, "
        f"and copied {latest.relative_to(ROOT)} -> {target.relative_to(ROOT)}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
