/* This file is generated by scripts/build_public_data.py. Do not edit manually. */

import digest20260902 from "../daily/2026/09/2026-09-02.json";
import digest20260901 from "../daily/2026/09/2026-09-01.json";
import digest20260831 from "../daily/2026/08/2026-08-31.json";
import digest20260830 from "../daily/2026/08/2026-08-30.json";
import digest20260829 from "../daily/2026/08/2026-08-29.json";
import digest20260828 from "../daily/2026/08/2026-08-28.json";
import digest20260827 from "../daily/2026/08/2026-08-27.json";

export const generatedDigests = [
  digest20260902,
  digest20260901,
  digest20260831,
  digest20260830,
  digest20260829,
  digest20260828,
  digest20260827,
] as const;

export const generatedDigestDates = [
  "2026-09-02",
  "2026-09-01",
  "2026-08-31",
  "2026-08-30",
  "2026-08-29",
  "2026-08-28",
  "2026-08-27",
] as const;
