/* This file is generated by scripts/build_public_data.py. Do not edit manually. */

import digest20260925 from "../daily/2026/09/2026-09-25.json";
import digest20260924 from "../daily/2026/09/2026-09-24.json";
import digest20260923 from "../daily/2026/09/2026-09-23.json";
import digest20260922 from "../daily/2026/09/2026-09-22.json";
import digest20260921 from "../daily/2026/09/2026-09-21.json";
import digest20260920 from "../daily/2026/09/2026-09-20.json";
import digest20260919 from "../daily/2026/09/2026-09-19.json";
import digest20260918 from "../daily/2026/09/2026-09-18.json";
import digest20260917 from "../daily/2026/09/2026-09-17.json";
import digest20260916 from "../daily/2026/09/2026-09-16.json";
import digest20260915 from "../daily/2026/09/2026-09-15.json";
import digest20260914 from "../daily/2026/09/2026-09-14.json";
import digest20260913 from "../daily/2026/09/2026-09-13.json";
import digest20260912 from "../daily/2026/09/2026-09-12.json";
import digest20260911 from "../daily/2026/09/2026-09-11.json";
import digest20260910 from "../daily/2026/09/2026-09-10.json";
import digest20260909 from "../daily/2026/09/2026-09-09.json";
import digest20260908 from "../daily/2026/09/2026-09-08.json";
import digest20260907 from "../daily/2026/09/2026-09-07.json";
import digest20260906 from "../daily/2026/09/2026-09-06.json";
import digest20260905 from "../daily/2026/09/2026-09-05.json";
import digest20260904 from "../daily/2026/09/2026-09-04.json";
import digest20260903 from "../daily/2026/09/2026-09-03.json";
import digest20260902 from "../daily/2026/09/2026-09-02.json";
import digest20260901 from "../daily/2026/09/2026-09-01.json";
import digest20260831 from "../daily/2026/08/2026-08-31.json";
import digest20260830 from "../daily/2026/08/2026-08-30.json";
import digest20260829 from "../daily/2026/08/2026-08-29.json";
import digest20260828 from "../daily/2026/08/2026-08-28.json";
import digest20260827 from "../daily/2026/08/2026-08-27.json";

export const generatedDigests = [
  digest20260925,
  digest20260924,
  digest20260923,
  digest20260922,
  digest20260921,
  digest20260920,
  digest20260919,
  digest20260918,
  digest20260917,
  digest20260916,
  digest20260915,
  digest20260914,
  digest20260913,
  digest20260912,
  digest20260911,
  digest20260910,
  digest20260909,
  digest20260908,
  digest20260907,
  digest20260906,
  digest20260905,
  digest20260904,
  digest20260903,
  digest20260902,
  digest20260901,
  digest20260831,
  digest20260830,
  digest20260829,
  digest20260828,
  digest20260827,
] as const;

export const generatedDigestDates = [
  "2026-09-25",
  "2026-09-24",
  "2026-09-23",
  "2026-09-22",
  "2026-09-21",
  "2026-09-20",
  "2026-09-19",
  "2026-09-18",
  "2026-09-17",
  "2026-09-16",
  "2026-09-15",
  "2026-09-14",
  "2026-09-13",
  "2026-09-12",
  "2026-09-11",
  "2026-09-10",
  "2026-09-09",
  "2026-09-08",
  "2026-09-07",
  "2026-09-06",
  "2026-09-05",
  "2026-09-04",
  "2026-09-03",
  "2026-09-02",
  "2026-09-01",
  "2026-08-31",
  "2026-08-30",
  "2026-08-29",
  "2026-08-28",
  "2026-08-27",
] as const;
