/* This file is generated by scripts/build_public_data.py. Do not edit manually. */

import digest20260830 from "../daily/2026/08/2026-08-30.json";
import digest20260829 from "../daily/2026/08/2026-08-29.json";
import digest20260828 from "../daily/2026/08/2026-08-28.json";
import digest20260827 from "../daily/2026/08/2026-08-27.json";

export const generatedDigests = [
  digest20260830,
  digest20260829,
  digest20260828,
  digest20260827,
] as const;

export const generatedDigestDates = [
  "2026-08-30",
  "2026-08-29",
  "2026-08-28",
  "2026-08-27",
] as const;
